# Modul 1 : Python for Data Science

First we will learn about basic programming with Python to utilize it's library and usage in data science

Let's learn. 

___ 
## Introduction to Python
Python is the world's fastest growing programming language. It used not only by Software Engineers, Mathematicians, Data Analysts, Scientist, Accountants, Network Engineers and even kids because it's ideal programming languange to learn first.
1. Solve complex problems in __less time__ with __fewer lines of code__
2. Python is multi-purpose language
3. Python is High-level language, Cross-platform, having Huge Community and Large Ecosystem of Library, frameworks and tools


### 1. REPL

![repl](https://github.com/BenedictusAryo/documents_assets/raw/master/New%20CourseMap/exercise_assets/repl.gif)

### 2. IPython

![ipython](https://github.com/BenedictusAryo/documents_assets/raw/master/New%20CourseMap/exercise_assets/ipython.gif)

### 3. IPython Notebook --> Jupyter Notebook


___
## Basic Python


### 1. Print Function
* print()
* print formatting

Print is built-in function in python. to use print function, type `print()`

**Exercise:** `print("Hello world")`

**Exercise:** print your name and age

In [ ]:
print("Hello world")

Hello world


**Print Formatting**

```python
name = Aryo
print("Hello, my name is {}. Nice to meet you !".format(name))
```

### Binar test markdown

In [ ]:
name =
print("Hello, nama saya {}. Senang kenalan sama kamu!".format(name))

Hello, nama saya 10. Senang kenalan sama kamu!


## 2. Variable

We use Variable to store data in memory

Example :
```python
students_count = 1000
```

In [ ]:
students_count = 1000
print(students_count)
type(students_count)

1000


int

In [ ]:
x = 4
y = 1

print(x+y)

5


## 3. Data Type

What kind of data that we can save in the variable ?

Python will automatically assign the data type. 

```python
students_count = 100
rating = 4.99
is_published = True
course_name = "Python Programming"
```

to check the datatype you can use `type()`

In [ ]:
students_count = 100 (int)
rating = 4.99 # Float (0 - ,.....)
is_published = True  #boolean (True / False)
course_name = "Python Programming"

In [ ]:
type(students_count)

int

In [ ]:
type(rating)

float

In [ ]:
type(is_published)

bool

In [ ]:
type(course_name)

str

In general, there are 3 data types:
- Integer
- Float
- String

### Integer
**Exercise:** Insert following number, assign to variable, then print them

```python
apel = 4
jeruk = 5
total_buah = apel + jeruk

print(total_buah)
```

In [ ]:
apel = 4
jeruk = 5
total_buah = apel + jeruk

print(total_buah)

9


In [ ]:
apel = "Halo"
jeruk = "Mas Kasa"
total_buah = apel + jeruk

print(total_buah)

HaloMas Kasa


### Float

The float type in Python designates a floating-point number. `float` values are specified with a decimal point.[more-resource](https://realpython.com/python-data-types/)

```python
panjang = 10.5
lebar = 4.6
```

In [ ]:
panjang = 10.5
lebar = 4.6

**Exercise:** Create variable called `luas` which `panjang * lebar`. And check data type of `luas`

In [ ]:
luas = panjang * lebar

In [ ]:
type(luas)

float

### Boolean

only consist of `True` or `False` value with capital T and F

```python
is_published = True
type(is_published)
```

In [ ]:
is_published = False
type(is_published)

bool

In [ ]:
is_published = False
if is_published == True:
  print("Lanjut")
else:
  print("Stop")

Stop


### String

Strings are sequences of character data. The string type in Python is called `str`.

String literals may be delimited using either single or double quotes. All the characters between the opening delimiter and matching closing delimiter are part of the string [more-resource](https://realpython.com/python-data-types/)

**Note:** String should be delimited using `'string' or "string"`

**Exercise:**  create variable called `kalimat` with below sentences and print them
```
That's why I Love you
```

In [ ]:
kalimat = "That's why i Love you"

In [ ]:
kalimat

"That's why i Love you"

### Built-in Function for string
#### len()
we can use function `len()` to count the length of value and _argument_ of value/variable you want to count.
```python
course = "Make-AI Data Science Course"
len(course)
```

In [ ]:
course = "Make-AI Data Science Course"
len(course)

27

In [ ]:
if len(course) == 25:
  print("Lanjut")
else:
  print("Stop")

# len(course)

Stop


#### String Method 

We can use function `.upper()`, `.lower()` and also `.title()` 

Given this variable:
```python
course = 'daTa sCience'
```
Make the `course` string
* uppercase: DATA SCIENCE
* Capitalize: Data science
* lowercase: data science
* Capitalize each word: Data Science

In [ ]:
course = 'daTa sCience'

course.upper()

'DATA SCIENCE'

In [ ]:
course.lower()

'data science'

In [ ]:
course.title()

'Data Science'

To remove the white space, we can use function `.strip()`, `lstrip()`, `.rstrip()`.

We can also replace with `.replace("old", "new")`


_Practice :_
```python
course = "  Make-AI Data Science Course "
```
Remove empty space before Make-AI and replace `Course` with `Learning`

In [ ]:
course = "Data Science"
print(course)

Data Science


#### String Slicing
Python string can use indexing to call some character. You can use bracket notation to get access to specific elements or characters
```python
course = "Make-AI Data Science Course"
course[0]
course[-1]
course[0:3]
course[4:]
course[:3]
course[:]
```

In [ ]:
course = "Make-AI Data Science Course"
course[0]

'M'

In [ ]:
course[-1]

'e'

In [ ]:
course[0:4]

'Make'

In [ ]:
course[:4]

'Make'

In [ ]:
course = [[1, 2, 3, 4], [2,3.2, 4.0]]
print(course)

[[1, 2, 3, 4], [2, 3.2, 4.0]]


**Exercise:** Declare variable `nama` :
```python
nama = 'badillah'
```
Using print function using `nama` above, so it can print below result
```python
Halo, Nama saya Badillah, saya sering dipanggil Badi.
```

In [ ]:
nama = 'badillah'

In [ ]:
print("Halo, Nama Saya",nama, "saya sering dipanggil Badi")

Halo, Nama Saya badillah saya sering dipanggil Badi


#### Double Quotes and Single Quotes
1. Python can use double quote and single quote
2. Using Prefix \
3. Double \\ to add \ in the string
4. Add \n to print in the new line
5. To print multiple line of string you can use 3 times quote

**Exercise:** 
```python
message = """
Dear Diary,
Today was very bad day
"""
print(message)
```

In [ ]:
message = """
ini membuat logik cek true false
ini membuat logik cek true false
ini membuat logik cek true false
ini membuat logik cek true false
ini membuat logik cek true false
"""

print(message)


ini membuat logik cek true false ini membuat logik cek true false
ini membuat logik cek true false
ini membuat logik cek true false
ini membuat logik cek true false
ini membuat logik cek true false




#### String Formatting

```python
first_name = "Benedict"
last_name = "Aryo"
full_name = ?
```
**Concatenating String :**
```python
first_name + " " + last_name
```
**String Formatting :**
```python
# Method 1
"{} {}".format(first_name, last_name)"

# Method 2
f"{first_name} {last_name}"
```

In [ ]:
first_name = "Aryo"
last_name = "Benedict"
full_name = first_name + last_name

# print()
first_name + " " + last_name
# Method 1
"{} {} {}".format(first_name, last_name, full_name)

'Aryo Benedict AryoBenedict'

In [ ]:
#Method 2
f"{first_name} {last_name} {full_name}"

'Aryo Benedict AryoBenedict'

## 4. Data Structure
### 4.1. List
List is Built-in Data Structure in Python, to create list use `[]` square bracket.

_Practice :_
```python
letters = ["a", "b", "c"]
numbers = [1, 2, 3]
mixed = [1, "b", 3.5]
matrix = [[0, 1], [2, 3]]
nested = [1, 2, ["a", [3, 4], "b"]]
zeros = [0] * 5
combined = zeros + letters
list_func = list(range(20))
chars = list("Hello world")
```


In [ ]:
nested = [1, 2, ["a", [3, 4], "b"]]
print(nested)

[1, 2, ['a', [3, 4], 'b']]


#### Accessing element in list
To access element in list, we can use square bracket `[index]` with index number of the element wanted to slice the list

_Exercise :_
```python
vowels = ["a", "i", "u", "e", "o"]
```
1. Replace "a" with "A"
2. Get first 3 value
3. Get last 2 value

In [ ]:
vowels = ["a", "i", "u", "e", "o"]

vowels[0] = "A"
print(vowels)

['A', 'i', 'u', 'e', 'o']


In [ ]:
vowels = ["a", "i", "u", "e", "o"]

vowels[0] = "A"
print(vowels)

['A']


In [ ]:
print(vowels[0:3])

['A', 'i', 'u']


In [ ]:
print(vowels[-2:])

['e', 'o']


In [ ]:
print(vowels[3:])

['e', 'o']


#### Append element to list
using `list.append('new')`

**Exercise:**
```python
murid = ['Andi','Budi','Susi']
```
Add `'Yanti'` to the list `murid`

In [ ]:
murid = ['Andi', 'Budi', 'Susi']
murid.append("Yanti")
print(murid)

['Andi', 'Budi', 'Susi', 'Yanti']


### 4.2. Dictionary
Dictionary is collections of key, value pairs. We use Dictionary to map value to its key.
`name -> contact`

```python
point = {"x": 1, "y": 2}
point = dict(x=1, y=2)

```
Because Dictionary is ollections of key, value pairs we cannot access on item with numeric index
```python
point["x"]
```
Assign value / new value:
```python
point["x"] = 10
point["y"] = 20
```

In [ ]:
point = {
    "x": 1, 
    "y": 2
    }

print(point.get("x"))

#ini sering dipakai di JSON (javascript object notation)
#object/list/array -- simbolnya [] --> ada di dalam dictionary

#dictionary -- simbolnya {} --> adalah kumpulan dari object

1


In [ ]:
point = {"x": 1, "y": 2}
point = dict(x=1, y=2)

print(point["x"])

1


### 4.3. Tupple
Tupple is Data Structure of container in python that is _immutable_. in short, it's read-only list.

Usually we use parentheses `()` to define a tupple
```python
point = (1, 2)
type(point)
``` 
_Exercise :_
```python
points = (1, 2) + (3, 4)
repetition = (1, 2) * 3
```
Tupple is immutable (cannot be changed)
```python
point[0] = 3
```

In [ ]:
point = (1, 2)
point = point * 2
print(point[1])
point[-2:]

2


(1, 2)

#### Swapping Variable
```python
x = 10
y = 20
```
_Exercise :_
**Swap the value x to 20 and y to 10**

In [ ]:
x = 10
y = 20

print('x', y)
print('y', x)

x 20
y 10


## 5. Comparison Operator
We use Comparison Operator to __compare value__.
```python
10 > 3
10 >= 3
3 == 50
10 == "10"
20 != "20"
"bag" > "apple"
"bag" == "BAG"
```
We sort "bag", it's comes after "apple" so, it's considered as __Greater__

Confused ?
Use function `ord()`
```
ord("b")
ord("B")
```

In [ ]:
x = 10
y = "sepuluh"

if type(x) != int:
  print("benar")

In [ ]:
ord("a")

118

In [ ]:
ord("b")

98

## Control Flow


### 6. Conditional Statement 
#### 6.1. If - Else
We use `if` to make decision expression
```python
temperature = 38

if temperature > 36:
    print("You have a fever")
else:
    print("You are cold")
```
What if `temperature = 15` ?


In [ ]:
temperature = 15

if temperature > 36:
    print("You have a fever")
else:
    print("You are cold")

You are cold


In [ ]:
temperature = 15

if temperature == 15:
    print("You have a fever")
else:
    print("You are cold")

You have a fever


#### 6.2. If - Elif
We use `Elif` for multiple condition
```python
temperature = 33

if temperature > 36:
    print("You have a fever")
elif temperature < 34:
    print("You're cold")
else:
    print("Normal body temperature")
```

In [ ]:
temperature = 33

if temperature > 36:
    print("You have a fever")
elif temperature < 34:
    print("You're cold")
else:
    print("Normal body temperature")

You're cold


In [ ]:
# buat range 34 ... 37 
# < 34 maka you're cold
# > 36 maka you have a fever
# xn....., 32, 33 maka Normal body temperature

### 7. For Looping
What if we want to iterate some task multiple times? We can use `for` loops.
```python
print("Sending a message")
print("Sending a message")
print("Sending a message")
print("Sending a message")
print("Sending a message")
```
We can use for loops :
```python
for number in range(3):
    print("Sending a message")
```

In [ ]:
for number in range(3):
    print("Sending a message")

Sending a message
Sending a message
Sending a message


#### Exercise :
Create for loops that print :
```
Attempt 1
Attempt 2
Attempt 3
Attempt 4
Attempt 5
```

In [ ]:
for number in range(5):
    print(f"Attempt {number+1}")

Attempt 1
Attempt 2
Attempt 3
Attempt 4
Attempt 5


In [ ]:
for number in range(5):
    print("Attempt", number+1)

Attempt 1
Attempt 2
Attempt 3
Attempt 4
Attempt 5


#### Exercise :
Create for loops that print :
```
Attempt .
Attempt ..
Attempt ...
Attempt ....
Attempt .....
```

In [ ]:
for i in range(1, 6):
    print("Attempt" + "." * i)

Attempt.
Attempt..
Attempt...
Attempt....
Attempt.....


#### Combined with conditional statement
1-10 bilangan genap saja

```python
for i in range(1,11):
    if i%2 == 0:
        print(i)
```

In [ ]:
for i in range(1,11):
    if i%2 == 0:
        print(i)

2
4
6
8
10


### 8. While Looping
While loop used when we want to repeat something `when the condition is True`. We Evaluating first then loops if the condition is still comply

**Loop until angka = 10**
```python
angka = 1
while angka < 10:
    print(angka)
    angka += 1
```


In [ ]:
angka = 1
while angka < 10:
    print(angka)
    angka += 1

1
2
3
4
5
6
7
8
9


### 10. Function
To create function start with keyword `def` then name then using `:`

```python
def greet():
    print("Hi there")
    print("Welcome aboard")
    
greet()
```
Function with input using parameters
```python
def greet(first_name, last_name):
    print(f"Hi {first_name} {last_name}")
    print("Welcome aboard")
    
greet("Benedict")
```
Error ?

In [ ]:
#membaut banyak proses dalam 1 perintah, yaitu perintah greet()
angka = 1
def greet():
    print("Hi there")
    print("Welcome aboard")
    if angka == 1:
      print("benar")
    
greet()

Hi there
Welcome aboard
benar


### Print with return value
```python
def tambah(angka1, angka2):
    return angka1 + angka2
    
    
jumlah = tambah(20, 30)
```

In [ ]:
def tambah(angka1, angka2):
    return angka1 + angka2

jumlah = tambah(20,30)
print(jumlah)

50


___
## Numpy (Numerical Python)
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more. [more-resource](https://docs.scipy.org/doc/numpy-1.13.0/user/whatisnumpy.html)
### 1. Importing package
we import numpy using keyword `import`

```python
import numpy
```

In [ ]:
import numpy

### Import using Alias

to make function calls quick, we can also abbreviate or create alias when we import the package

```python
import numpy as np
```

In [ ]:
import numpy as np

### 2. Numpy Array
At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences

**Let's compare the data structure**

For example we have **3 rectangle** which each having `panjang` and `lebar` <br>
create standard `list` called `panjang` and `lebar`
```python
panjang = [4,5,6]
lebar = [3,4,5]
```
Create variable `luas` which is `panjang` * `lebar`

In [ ]:
import numpy as np
panjang = [4,5,6]
lebar = [3,4,5]

print(np.array([[panjang], [lebar]]))

[[[4 5 6]]

 [[3 4 5]]]


There's `TypeError: can't multiply sequence by non-int of type 'list'`

`list` data cannot do multiplication, or you can using for loop to do multiplication each element which is not efficient.

Otherwise you can use `Numpy array` data type
```python
# Numpy already imported as np

panjang = np.array([4,5,6])
lebar = np.array([3,4,5])
```


In [ ]:
panjang = np.array([4,5,6])
lebar = np.array([3,4,5])

Check Datatype of `panjang` and `lebar` using `type()`

In [ ]:
type(lebar)

numpy.ndarray

Now Declare variable `luas` which is `panjang` times `lebar`
```python
luas = panjang * lebar
```
Then print the `luas` result

In [ ]:
luas = panjang * lebar

### 3. Array Shape
in the example above when we check _datatype_ using `type(luas)` we will get output 
```python
numpy.ndarray
```
Means that the datatype of `luas` is `N dimensional Array of Numpy`

to check the `N` or **Array shape** we can use _attribute_ `.shape` 
```
luas.shape
```

In [ ]:
luas.shape

(3,)

Now, create new array below:
```python
matrix = np.array([[1,2,3],
                   [4,5,6]])
```
_Be careful with [ ] marks_

In [ ]:
matrix = np.array([[1,2,3],
                   [4,5,6]])

Then, print and check `.shape` of the `matrix`, compare with `luas`

What is the differences ?

In [ ]:
matrix.shape

(2, 3)

In [ ]:
luas.shape

(3,)

### 4. Array Reshaping

Let's take a look of our `matrix` array:
```python
array([[1, 2, 3],
       [4, 5, 6]])


print(matrix.shape)

(2, 3)
```

In [ ]:
np.array([[1, 2, 3],
       [4, 5, 6]])

print(matrix.shape)

(3, 2)


Using `.reshape(x,y)` method function, try to create this array called `new_matrix`
```python
array([[1, 2],
       [3, 4],
       [5, 6]])
```

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# melakukan reshape menjadi array 3x2
arr_reshaped = arr.reshape(3, 2)

# mencetak array baru yang sudah di reshape
print(arr_reshaped)

[[1 2]
 [3 4]
 [5 6]]


## Logical Operators

In [ ]:
a = 7
b = 8

In [ ]:
# and
# Jika keduanya benar, maka True
print(a == 8 and b == 8)

False


In [ ]:
# or
# Jika salah satu benar, maka True
print(a == 7 or b == 7)

True


## Break Statement
Break Statement digunakan untuk menyetop suatu proses perulangan.

In [ ]:
for val in "binar":
    print(val)
    if val == "a":
        break

b
i
n
a


## Continue Statement

Continue Statement digunakan untuk melakukan skip suatu code.

In [ ]:
for val in "binar":
    if val == "a":
        continue
    print(val)

b
i
n
r


# Pass Statement

In [ ]:
sequence = ['a', 'b', 'c']
for val in sequence:
  if val == 'c':
    print("oke")
  else:
    pass

oke


# Function

Function atau Fungsi adalah sebuah kumpulan script untuk spesifik task

**Fungsi tanpa Parameter**

In [ ]:
def add_numbers():
  sum = 1 + 2
  return sum


add_numbers()

3

**Fungsi dengan Parameter**

In [ ]:
def add_numbers(a, b, c):
  sum = a + b + c
  return sum

add_numbers(1, 2, 5)

8

**Fungsi dengan Default Parameter**

In [ ]:
def add_numbers(a=1, b=2):
  sum = a + b
  return sum

In [ ]:
add_numbers()

3

In [ ]:
add_numbers(3, 3)

6

# Lambda Function

Lambda: Fungsi yang tidak memiliki nama

In [ ]:
data = lambda x: x * 2

print(data(5))

10


# File I/O

File I/O perintah dalam Python yang digunakan ketika berhubungan dengan file. Diantaranya:


1.   Write File
2.   Open File



**Write File**

In [ ]:
with open("names.txt",'w',encoding = 'utf-8') as f:
   f.write("db1.sql\n")
   f.write("db2.sql\n")
   f.write("Dono\n")
   

**Read File**

In [ ]:
f = open("/content/names.txt",'r',encoding = 'utf-8')
print(f.read())

Ari
Dino
Dono

